### ISSUE TITLE
[Feature] Get all whitelisted collateral

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#132]
## Feature Description

Add a get all of the whitelisted collateral to the BondFactory.

**Comment by aodhgan** [comment]
@CjHare Interested in taking this one. 
How do we want this to be implemented? Change the underlying symbol => address mapping data structure? What are you thinking?

**Comment by CjHare** [comment]
This would a getter function on `CollateralWhitelist`

`whitelistedSymbols`, returning an array of symbols (keys to the mapping), with those being used with the existing `whitelistedCollateralAddress` to retrieve the token contract per a symbol.

On-chain support for investigating which contract we're using for the collateral symbol.
