### ISSUE TITLE
[Feature] String data field on Slash

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#141]
## Feature Description

When the owner slashes the bond, add a string field for a text area input to record a reason.

The reason must be retrievable, but not editable.

**Comment by afkbyte** [comment]
Are you opposed to having the string reason being emitted as a part of a slash event? Would be retrievable and save on gas wrt to storage slots utilized.

**Comment by CjHare** [comment]
Yeah, that was my first thought too. As I recall the requirements turned out to be on-chain storage, or rather both via event & storage.

Supporting thegraph caching and on-chain retrieval.

**Comment by aodhgan** [comment]
closed by #219
