### ISSUE TITLE
[Feature] Api Version

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#156]
## Feature Description

Create an abstract contract for the API version of all contracts.

This needs to checked when a release is performed (chosen release semver matches APi version).

**Comment by CjHare** [comment]
This is not only the abstract contract (i.e. all children share the same versioning), but also the check trigger on release.

**Comment by CjHare** [comment]
When release of `0.0.1` the version returned by the contract needs to be `0.0.1`, enforced somehow, maybe github release

**Comment by CjHare** [comment]
This is ensure the GitHub release version matches the code version

**Comment by CjHare** [comment]
Thinking about this, the trigger condition needs to be a new tag rather than the GitHub release event, which is created as part of GUI release process but will also cater for any CLI release process.

Example GitHub trigger 
https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags

**Comment by aodhgan** [comment]
closed by #171
