### ISSUE TITLE
[Feature] Admin / permission

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#172]
## Feature Description

Standard admin/operator roles.

```
Super Admin - top level role permission settings (add and remove admins)
Admin - product related permission settings, override, contract freeze, operator selection
Operators - product related parameter settings and actions (e.g. bond quote, arbiters, whitelisting, reward parameters)
```

Questions still to answer:
...who upgrades contracts?
...who deploys contract?

Find out those answers & implement for bonds.

**Comment by afkbyte** [comment]
would we want to use the openzeppelin Roles based access control (or a lighter weight variation thereof) for roles and role assignment? We could give super admin role to the deployer when the contract is initialized.

**Comment by CjHare** [comment]
https://www.notion.so/windranger-io/Roles-Permissions-948497c770d7498f906809b5e9dc3229
```
**Super-Admin:**

- Can add/remove an admin to any organization (including self)
- Initialize an organization and add an admin to it

**Admin:**

- Update information for their organization page
- Add/remove additional admins and operators to their page
- Manage ownership of the contract
- + all operator abilities

**Page Operator:**

- Create new pools/bonds (define pool/bond parameters)
- Manage existing pools/bonds (manual release of funds, slashing, etc.)

**User:**

- Search through organizations and view open or active bonds/pools
- Can stake/commit collateral to pools to become a guarantor/staker

**Guarantor/Staker:**

- Redeem rewards when bond/pool criteria is met
- View ‘my pools/bonds’
```

**Comment by CjHare** [comment]
https://www.notion.so/windranger-io/Roles-Permissions-948497c770d7498f906809b5e9dc3229 has been updated

**Comment by CjHare** [comment]
Function for convenience Admin.

Create another interface to provide convenience functions for managing the adding / removing of users (propagates to the others)

**Comment by CjHare** [comment]
Include treasury roles into modifiers.

Removes the dependency on needing to know the role Id, easier to read? Abstraction can provide a single point to switch around how we implement the storage / evaluation.
