### ISSUE TITLE
[Feature] Pausability

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#187]
## Feature Description

Add `PausableUpgradeable` with permission guarding and tests to `BondFactory` and `BondMediator`.

## Additional Information

Once this is done, spawn a ticket to refactor the permissions (AccessControl), pausability and upgradability into a new abstract parent for the `BondFactory`, `BondMediator` and `BondManager`. 
Also refactor the testing, so it done only once in the parent and not in the test classes for each (no duplication)

**Comment by CjHare** [comment]
Permissions have now been refactored, that part no longer needs doing.

**Comment by aodhgan** [comment]
closed by #204
