### ISSUE TITLE
[Feature] Local & CI test setup for TheGraph bindings

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#205]
## Feature Description

Need to be able to test the Subgraph bindings (conversion of Eth events to data storage), locally & in CI rather than relying on Subgraph studio, which is neither local or CI, but against a test network with notable delays.

## Additional Information

Details on setting up a local Subgraph.
https://medium.com/coinmonks/deploy-subgraphs-to-any-evm-aaaccc3559f

Run Gnache with Hardhat in local RPC mode (this may interesting to get working on both CI and local)
https://hardhat.org/getting-started/#connecting-a-wallet-or-dapp-to-hardhat-network

**Comment by CjHare** [comment]
Also PoolTogether example https://github.com/pooltogether/pooltogether-subgraph-v3/tree/a2ea66a9b7f76d8f6c0bac39d03f9974e35f3973

**Comment by grezle** [comment]
Theres also https://github.com/LimeChain/matchstick-as for testing the mappings from mocked event values 🚀

**Comment by aodhgan** [comment]
closed by https://github.com/windranger-io/windranger-treasury-subgraph
