### ISSUE TITLE
[Feature] Provide whitelisted query by address

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#212]
## Feature Description

`BondMediator` 

Has `createManagedBond` function containing:
```
    string memory collateralTokenSymbol =   IERC20MetadataUpgradeable(collateralTokens).symbol();
```    

That line must be removed, by providing:
```
    function _isCollateralWhitelisted(isWhitelisted address) internal view returns (bool)
```

## Additional Information

Additional test case for the Mediator:
- Creation using a non-whitelisted token that has the same symbol as a whitelisted e.g. whitelist BIT, create another with the same symbol BIT and expect test to revert (as the contract address is different)

**Comment by aodhgan** [comment]
Think this is being covered as part of #215

**Comment by CjHare** [comment]
This is a TODO from my re-factoring, unsure whether that's change (the one mentioned) has made it to master yet 🤔

**Comment by CjHare** [comment]
...and it's gone!
