### ISSUE TITLE
[Bug] Gas Consumption in _enforceUniqueRewardTokens()

### ISSUE THREAD

**Issue by joigno** [windranger-io/windranger-treasury#330]
## Bug Description

TimeLockMultiRewardBond: Double-loop on _enforceUniqueRewardTokens() to avoid duplicates. Can be linear with a counter and a mapping? (same for StakingPool)

## Current Behaviour

Quadratic behavior in gas consumption.

## Expected Behaviour

Using a Counter of something linear should scale better in Gas.

**Comment by CjHare** [comment]
Closed by https://github.com/windranger-io/windranger-treasury/pull/335
