### ISSUE TITLE
[Bug] StakingPoolFactory missing params

### ISSUE THREAD

**Issue by aodhgan** [windranger-io/windranger-treasury#365]
## Bug Description

consider emitting both `maxTotalPoolStake` and `minTotalPoolStake` from StakingPoolCreated event

## Steps to Reproduce 

1.
2.
3.
4.

## Expected Behaviour

##Additional Information

**Comment by octavioamu** [comment]
thanks @aodhgan , just for context, this is a very important piece for the UI, needed to build the displayed data, like the progress bar and states.

**Comment by CjHare** [comment]
@octavioamu so you are saying, this is less of 'consider implementing' rather it's  'essential to implement' 😉

**Comment by octavioamu** [comment]
yep it is essential to implement I cannot build the UI without it. all those bar need to know the totals to render https://bonds-5nzdu6djp-windranger.vercel.app/pools?dao=bitdao
