### ISSUE TITLE
[Feature] Implement bond contract as treasury asset class

### ISSUE THREAD

**Issue by shahankhatch** [windranger-io/windranger-treasury#4]
## Feature Description

This repo doesn't yet contain any treasury smart contracts. 

Let's implement a smart contract for the current bond specification and flow from the following:
- https://github.com/windranger-io/governance/issues/18
- https://github.com/windranger-io/governance/issues/23

**Comment by CjHare** [comment]
question: Do we want the Treasury to keep a reference to the various Bonds it is the Treasury for?

This would have to be done as part of the bond creation process (for single bonds, in factory), but if the Treasury knew of the Bonds that it could receive slashing funds from, then we give a account of the assets & liabilities including the bonds (additional work for the Treasury to aggregate the bonds).

**Comment by shahankhatch** [comment]
I suggest we don't keep track of the upstream bonds in the treasury, since the bond is not required to update downstream records, e.g., in a scenario where the treasury address of a the bond changes.

**Comment by CjHare** [comment]
No longer required,
