### ISSUE TITLE
[Feature] Write specification for bond smart contract

### ISSUE THREAD

**Issue by shahankhatch** [windranger-io/windranger-treasury#5]
## Feature Description

The current treasury specifications deal specifically for the inbound and outbound treasury for BitDAO. There are other treasury modules that we need to specify and implement to support the core treasury. 

For this issue, create a specification of a bond contract which supports the following:
- a bond record can be instantiated by any user
- any user can contribute to a bond record
- each contribution issues a fungible token, but only for this particular bond
- all contributions are locked within the bond record until redemptions are enabled
- redemptions can only be enabled by the redeem approver (usually a multi-sig)
- a user that submits a number of fungible tokens redeems an equivalent amount of their contribution
- a redemption may additionally mint and issue a reward token/nft

The use case and initial data structure describing the use of the bond contract is here:
https://github.com/windranger-io/governance/blob/main/docs/use_cases.md

**Comment by CjHare** [comment]
The spec for the single bond contract now exists:
https://github.com/windranger-io/windranger-treasury/blob/a61a55bfd6f7cc6dc0891d655975f6229e2f3172/docs/specs/bond_single.md

With supporting sequence diagram:
https://github.com/windranger-io/windranger-treasury/blob/a61a55bfd6f7cc6dc0891d655975f6229e2f3172/docs/specs/bonding.puml

**Comment by CjHare** [comment]
@shahankhatch Can we close this issue, or are further details needed in the Bond spec?

**Comment by shahankhatch** [comment]
Thanks @CjHare!
