### ISSUE TITLE
[Feature] To know whether there has been a slash event

### ISSUE THREAD

**Issue by CjHare** [windranger-io/windranger-treasury#59]
## Feature Description

The front end needs to know whether a slash event has ocurcred for a Bond.

## Additional Information

Although an event is emitted, a direct query of state is required with this signature:
```
  function hasSlashingOcurred() public view returns (bool)
```

**Comment by CjHare** [comment]
@octavioamu Let me know whether you'll still need this feature ...otherwise I'll close the ticket.

**Comment by octavioamu** [comment]
Well all depends on what we want to build in terms of UI, but for sure if we want to show a dashboard with the bond data that will be end needed to show the real state of the bond.

**Comment by CjHare** [comment]
It is sounding like you do not know of a requirement to show that 🤔 

Another challenge on displaying whether a bond has been slashed is that the contract allows for a bond to be slashed multiple times. Another piece of data that could be displayed, but I don't know whether that'll actually ever happen. or if it does, how often, or what the user would want to see.

@edenkidane Do you have any further details on the requirements for displaying of slashed status?

**Comment by edenkidane** [comment]
There should be a "details" or "more info" button (the mockups shows it as a lightning bolt). If a bond is slashed, its  status can appear https://www.figma.com/file/HvuU7z7xxmQcd1OLFOv86J/Bonds?node-id=0%3A1

Since there is only one guarantor in the MVP and not multiple, is there a way for the singular guarantor bond to be slashed multiple times ?

**Comment by CjHare** [comment]
@edenkidane could you give me access to that Figma please 😁 

My understanding of supporting multi slashes: multi-step / multi-date performance factors being evaluated individually.

**Comment by CjHare** [comment]
Okay, after checking out the Figma, I propose the Bond perform double accounting, exposing the sums for the front end.
(Events are emitted already containing this data, but keeping the sums and allowing retrieval is likely to be also useful later on chain).

The additional methods would be created on the Bond contract:
```
// Number of debt tokens held by Guarantors
function debtTokensOutstanding() external view returns (uint256)

// Number of debt tokens still held by the Bond (amount of Guarantor deposits still needed)
function debtTokensRemaining() public view returns (uint256)

// Number of collateral tokens (BIT initially) held by the Bond
function collateralHeld() external view returns (uint256)

// Number of collateral tokens that have been slashed
function collateralSlashed() external view returns (uint256)
```

Using the four new methods the 'more details' page can display that information and the bond status bar UI element could be calculated as follows:
```
if(  debtTokensRemaining == 0 ) {
  // Bond has full collateral, display 100% full and turn bar green (sucess)
} else {
  // Bond progress as a decimal (multiply by 100 for a percentage)
  progress = debtTokensOutstanding / totalSupply 
}
```
`totalSupply` method already exists on the Bond contract as it extends `ERC20`, a wrapper method can be created if a different name is desired, just let me know.

**Comment by octavioamu** [comment]
That is great Chris, one question about fetching that data, are we planning to use thegraph? Or all the data will be fetched by the contract methods only? Kind of worry on itinerate all those contracts to fetch the data and show the UI

**Comment by octavioamu** [comment]
Another question is will be all the amounts expressed in BIT?

**Comment by edenkidane** [comment]
Initially yes all amounts will be expressed in BIT, however in the future we will likely support ETH, maybe stables.

**Comment by CjHare** [comment]
@octavioamu FYI there is a ticket to (add whitelisting for the collateral token)[https://github.com/windranger-io/windranger-treasury/issues/52]. That'll provide an easy way to have any collateral token.

Yes, you're right, using the thegraph would make the front end much nicer and more performant 👍 

The contract code was there to convey the logic (which can all be put into GraphQL statement).

**Comment by CjHare** [comment]
fYI - for language consistency the debt tokens and collateral getters will have their names trimmed to:

```
// Number of debt tokens still held by the Bond (amount of Guarantor deposits still needed)
function debtTokens() public view returns (uint256)

// Number of collateral tokens (BIT initially) held by the Bond
function collateral() external view returns (uint256)
```
